<?php

namespace Richpolis\PublicidadBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PublicidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicidadRepository extends EntityRepository
{
    
}
