#richpolis_shopping_cart:
#    resource: "@RichpolisShoppingCartBundle/Controller/"
#    type:     annotation
#    prefix:   /

publicidad:
    resource: "@PublicidadBundle/Controller/"
    type:     annotation
    prefix:   /backend

galerias:
    resource: "@GaleriasBundle/Controller/"
    type:     annotation
    prefix:   /backend

paginas:
    resource: "@PaginasBundle/Controller/"
    type:     annotation
    prefix:   /backend

frontend:
    resource: "@FrontendBundle/Controller/"
    type:     annotation
    prefix:   /

backend:
    resource: "@BackendBundle/Controller/"
    type:     annotation
    prefix:   /backend

publicaciones:
    resource: "@PublicacionesBundle/Controller/"
    type:     annotation
    prefix:   /backend

_imagine:
    resource: .
    type:     imagine