<?php

namespace Richpolis\PublicacionesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ServicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicioRepository extends EntityRepository
{
    public function getMaxPosicion(){
        $em=$this->getEntityManager();
       
        $query=$em->createQuery('
            SELECT MAX(a.position) as value 
            FROM PublicacionesBundle:Servicio a 
            ORDER BY a.position ASC
        ');
        
        $max=$query->getResult();
        return $max[0]['value'];
    }
    
    public function findActivos(){
        $em=$this->getEntityManager();
        $query=$em->createQuery('
               SELECT a
               FROM PublicacionesBundle:Servicio a 
               WHERE a.isActive = :servicio
               ORDER BY a.position ASC
        ')->setParameters(array('servicio'=> true));
        
        return $query->getResult();
    }
}
