<?php

namespace Richpolis\ShoppingCartBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoriaProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaProductoRepository extends EntityRepository
{
}
