<?php

namespace Richpolis\ShoppingCartBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DetallePedidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetallePedidoRepository extends EntityRepository
{
}
